version: '3.3'
services:
  web:
    image: 'apachecustos/custos-admin-portal:latest'
    ports:
      - '443:443'
    volumes:
      - /Users/isururanawaka/Documents/Airavata_Repository/airavata-custos-portal/privkey.pem:/etc/nginx/privkey.pem
      - /Users/isururanawaka/Documents/Airavata_Repository/airavata-custos-portal/fullchain.pem:/etc/nginx/fullchain.pem
    environment:
      VUE_APP_CLIENT_ID: ''
      VUE_APP_CLIENT_SEC: ''
      VUE_APP_REDIRECT_URI: 'http://localhost:8080/callback'
      VUE_APP_CUSTOS_API_URL: 'https://custos.scigap.org/apiserver'
      VUE_APP_SUPER_CLIENT_ID: ''
      VUE_APP_UNDER_MAINTENANCE: false
